# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  packages:
    type: install
    name: openssh-client

  gpghome:
    type: copy
    path: /home/dodo/.gnupg
    image: dodo/gpg
