# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo

  packages:
    type: install
    name: azure-cli
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ buster main"
    gpg: "https://packages.microsoft.com/keys/microsoft.asc"
