# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  packages:
    type: install
    name: cron libsqlite3-0 vim

  env:
    type: environment
    variables:
      PATH: /opt/python/bin

  files:
    type: copy
    path: /
    directory: root

  khal:
    type: copy
    path: /opt/python
    dockerfile: |
      FROM dodo/languages/python
      ENV PATH /opt/python/bin:$PATH
      RUN pip3 install khal vdirsyncer requests-oauthlib

  setup:
    type: script
    script: |
      chmod u+s /usr/sbin/cron
      cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
      echo Europe/Berlin > /etc/timezone
