version: '3.7'

# TODO: handle bind mounts from the user's home directory properls
# - do not hard code the user names
# - encrypt secrets

services:
  init-volumes:
    image: dodo/base
    volumes:
      - 'tmux-data:/data/tmux'
      - 'zsh-data:/data/zsh'
      - 'vim-data:/data/vim'
      - 'gpg-data:/data/gpg'
      - 'pulseaudio:/data/pulseaudio'
      - 'scd:/data/pcscd'
      - 'sshconfig:/data/sshconfig'
      - 'awsconfig:/data/awsconfig'
      - 'kubeconfig:/data/kubeconfig'
      - 'passwords:/data/passwords'
      - '/Users/ole.claussen/.ssh:/home/dodo/.ssh'
      - '/Users/ole.claussen/.aws:/home/dodo/.aws'
      - '/Users/ole.claussen/.kube:/home/dodo/.kube'
    entrypoint:
      - /bin/sh
      - -euxc
      - |
        cp -r /home/dodo/.ssh/* /data/sshconfig/
        cp -r /home/dodo/.aws/* /data/awsconfig/
        cp -r /home/dodo/.kube/* /data/kubeconfig/
        chown -R dodo:dodo /data/*

volumes:
  tmux-data:
    name: tmux-data

  vim-data:
    name: vim-data

  zsh-data:
    name: zsh-data

  gpg-data:
    name: gpg-data

  sshconfig:
    name: sshconfig

  awsconfig:
    name: awsconfig

  kubeconfig:
    name: kubeconfig

  passwords:
    name: passwords

  pulseaudio:
    name: pulseaudio

  dbus:
    name: dbus

  scd:
    name: scd
