version: '3.7'

# TODO: handle bind mounts from the user's home directory properls
# - do not hard code the user names
# - encrypt secrets

services:
  init-volumes:
    image: dodo/base
    volumes:
      - 'tmux-data:/data/tmux'
      - 'zsh-data:/data/zsh'
      - 'jira-data:/data/jira'
      - 'vim-data:/data/vim'
      - 'gpg-agent:/data/gpg-agent'
      - 'pulseaudio:/data/pulseaudio'
      - 'scd:/data/pcscd'
      - 'kubeconfig:/data/kubeconfig'
      - 'passwords:/data/passwords'
      - 'vdir:/data/vdir'
    entrypoint:
      - /bin/sh
      - -euxc
      - chown -R dodo:dodo /data/*

volumes:
  tmux-data:
    name: tmux-data

  vim-data:
    name: vim-data

  zsh-data:
    name: zsh-data

  jira-data:
    name: jira-data

  gpg-agent:
    name: gpg-agent

  kubeconfig:
    name: kubeconfig

  passwords:
    name: passwords

  pulseaudio:
    name: pulseaudio

  dbus:
    name: dbus

  scd:
    name: scd

  vdir:
    name: vdir
