version: '3.7'

# TODO: handle bind mounts from the user's home directory properls
# - do not hard code the user names
# - encrypt secrets

services:
  init-volumes:
    image: docker
    volumes:
      - 'tmux-data:/data/tmux'
      - 'zsh-data:/data/zsh'
      - 'jira-data:/data/jira'
      - 'vim-data:/data/vim'
      - 'gpg-agent:/data/gpg-agent'
      - 'pulseaudio:/data/pulseaudio'
      - 'scd:/data/pcscd'
      - 'aws-cache:/data/aws-cache'
      - 'gcloud-data:/data/gcloud-data'
      - 'kubeconfig:/data/kubeconfig'
      - 'passwords:/data/passwords'
      - 'vdir:/data/vdir'
      - 'mail:/data/mail'
      - 'helm:/data/helm'
      - 'chirp:/data/chirp'
      - 'terraform:/data/terraform'
      - '/Users/ole.claussen:/Users/ole.claussen'
    entrypoint:
      - /bin/sh
      - -euxc
      - |
        cp /Users/ole.claussen/.chirp/* /data/chirp/
        chown -R 1000:1000 /data/*

volumes:
  tmux-data:
    name: tmux-data

  vim-data:
    name: vim-data

  zsh-data:
    name: zsh-data

  jira-data:
    name: jira-data

  gpg-agent:
    name: gpg-agent

  aws-cache:
    name: aws-cache

  gcloud-data:
    name: gcloud-data

  kubeconfig:
    name: kubeconfig

  passwords:
    name: passwords

  pulseaudio:
    name: pulseaudio

  dbus:
    name: dbus

  scd:
    name: scd

  vdir:
    name: vdir

  mail:
    name: mail

  helm:
    name: helm

  chirp:
    name: chirp

  terraform:
    name: terraform

  sbt-cache:
    name: sbt-cache
