version: '3.7'

services:
  tmux:
    build:
      context: tmux
    environment:
      - TMUX_TMPDIR=/var/lib/tmux
    volumes:
      - tmux-socket:/var/lib/tmux
    entrypoint: /server.sh
    container_name: tmux
    restart: always

volumes:
  tmux-socket:
    name: tmux-socket

  vim-data:
    name: vim-data
