version: '3.7'

services:
  tmux:
    build:
      context: tmux
    volumes:
      - 'tmux-data:/data/tmux'
      - 'zsh-data:/data/zsh'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/Users:/Users'
    environment:
      - 'TMUX_TMPDIR=/data/tmux'
    working_dir: '${HOMEDIR}'
    entrypoint: /session.sh
    container_name: tmux
    restart: always

volumes:
  tmux-data:
    name: tmux-data

  vim-data:
    name: vim-data

  zsh-data:
    name: zsh-data
