add_newline = false
format = "$directory$character"

[character]
success_symbol = '[\(](blue)'
error_symbol = '[\(](red)'
vicmd_symbol = "[|](blue)"

[directory]
format = '[\(](blue)[$path](yellow)[\)-](blue)'
