FROM dodo/languages/golang AS terraform-bundler

RUN apt-get update \
 && apt-get install -y git zip

RUN git clone --branch v0.11.14 https://github.com/hashicorp/terraform.git /terraform
RUN cd /terraform && go install ./tools/terraform-bundle

COPY terraform-bundle-0.11.14.hcl .

RUN /root/go/bin/terraform-bundle package terraform-bundle-0.11.14.hcl \
 && mkdir -p terraform-bundle \
 && unzip -d terraform-bundle terraform_*.zip

FROM dodo/base

RUN apt-get update \
 && apt-get -y install curl git gnupg jq

RUN curl -L -o /bin/kubectl \
    https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl \
 && chmod +x /bin/kubectl

COPY --from=dodo/aws /opt/python /opt/python
ENV PATH /opt/python/bin:$PATH

COPY --from=terraform-bundler /terraform-bundle/* /bin/
COPY --from=dodo/pass /bin/gopass /bin/gopass

USER dodo
COPY --chown=dodo:dodo --from=dodo/gpg /home/dodo/.gnupg/ /home/dodo/.gnupg
COPY --from=dodo/pass /home/dodo/.config/gopass/ /home/dodo/.config/gopass/
COPY --from=dodo/aws /home/dodo/.aws/ /home/dodo/.aws/
COPY --from=dodo/kube /home/dodo/.kubeconfig /home/dodo/.kubeconfig
COPY --chown=dodo:dodo home/ /home/dodo/
ENV KUBECONFIG /home/dodo/.kubeconfig
