# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo
  dotfiles: home

env:
  PATH: /opt/python/bin
  KUBECONFIG: /home/dodo/.kubeconfig

packages:
  name:
    - git
    - gnupg
    - openssh-client
    - jq

download:
  - source: https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_linux_amd64.zip
    unpack: terraform
    destination: /bin/terraform

  - source: https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
    destination: /bin/kubectl

from:
  - image: dodo/gpg
    path: /home/dodo/.gnupg
  - image: dodo/pass
    path: /bin/gopass
  - image: dodo/pass
    path: /home/dodo/.config/gopass
  - image: dodo/aws
    path: /home/dodo/.aws
  - image: dodo/kube
    path: /home/dodo/.kubeconfig
  - image: dodo/aws
    path: /opt/python
