# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo
  dotfiles: home

env:
  PATH: /opt/python/bin:/opt/google-cloud-sdk/bin

packages:
  name:
    - git
    - gnupg
    - jq

download:
  - source: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
    unpack: terraform
    destination: /bin/terraform

  - source: https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.3/terragrunt_linux_amd64
    destination: /bin/terragrunt

  - source: https://github.com/liamg/tfsec/releases/download/v0.10.0/tfsec-linux-amd64
    destination: /bin/tfsec

  - source: https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
    destination: /bin/kubectl

  - source: https://download.docker.com/linux/static/stable/x86_64/docker-19.03.13.tgz
    unpack: docker/docker
    destination: /bin/docker

  - source: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
    destination: /usr/lib/docker/cli-plugins/docker-buildx

  - source: https://github.com/mozilla/sops/releases/download/v3.6.1/sops-v3.6.1.linux
    destination: /bin/sops

from:
  - image: dodo/gpg
    path: /home/dodo/.gnupg
  - image: dodo/pass
    path: /bin/gopass
  - image: dodo/pass
    path: /home/dodo/.config/gopass
  - image: dodo/aws
    path: /home/dodo/.aws
  - image: dodo/aws
    path: /opt/python
  - image: dodo/google
    path: /opt/google-cloud-sdk
