# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  packages:
    type: install
    name: git gnupg openssh-client jq

  env:
    type: environment
    variables:
      PATH: /opt/python/bin
      KUBECONFIG: /home/dodo/.kubeconfig

  terraform:
    type: fetch
    source: https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_linux_amd64.zip
    unpack: terraform
    destination: /bin/terraform

  kubectl:
    type: fetch
    source: https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
    destination: /bin/kubectl

  gpghome:
    type: copy
    path: /home/dodo/.gnupg
    image: dodo/gpg

  pass:
    type: copy
    path: /bin/gopass
    image: dodo/pass

  passconfig:
    type: copy
    path: /home/dodo/.config/gopass
    image: dodo/pass

  awsconfig:
    type: copy
    path: /home/dodo/.aws
    image: dodo/aws

  kubeconfig:
    type: copy
    path: /home/dodo/.kubeconfig
    image: dodo/kube
