# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo

packages:
  name:
    - jq

download:
  - source: https://github.com/mikefarah/yq/releases/download/v4.22.1/yq_linux_amd64
    destination: /bin/yq
