# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  env:
    type: environment
    variables:
      DOCKER_TLS_CERTDIR: /certs

  packages:
    type: install
    name: btrfs-progs e2fsprogs iptables iproute2 openssl xfsprogs gnupg

  docker:
    type: fetch
    source: https://download.docker.com/linux/static/stable/x86_64/docker-19.03.13.tgz
    unpack: docker/docker
    destination: /bin/docker
    # TODO: same for ctr, runc, containerd-shim, docker-init, docker-proxy, dockerd, containerd

  dind:
    type: fetch
    source: https://raw.githubusercontent.com/docker/docker/ed89041433a031cafc0a0f19cfe573c31688d377/hack/dind
    destination: /bin/dind

  compose:
    type: fetch
    source: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    destination: /bin/docker-compose

  rootlesskit:
    type: fetch
    source: https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-19.03.13.tgz
    unpack: docker-rootless-extras/rootlesskit
    destination: /bin/rootlesskit
    # TODO: some for vpnkit, rootlesskit-docker-proxy, dockerd-rootless.sh

  ctop:
    type: fetch
    source: https://github.com/bcicen/ctop/releases/download/v0.7.5/ctop-0.7.5-linux-amd64
    destination: /bin/ctop

  buildx:
    type: fetch
    source: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
    destination: /usr/lib/docker/cli-plugins/docker-buildx

  pass:
    type: fetch
    source: https://github.com/gopasspw/gopass/releases/download/v1.14.3/gopass-1.14.3-linux-amd64.tar.gz
    unpack: gopass
    destination: /bin/gopass

  awsvault:
    type: fetch
    source: https://github.com/99designs/aws-vault/releases/download/v6.6.0/aws-vault-linux-amd64
    destination: /bin/aws-vault

  ecrhelper:
    type: fetch
    source: https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.5.0/linux-amd64/docker-credential-ecr-login
    destination: /bin/docker-credential-ecr-login

  dormouse:
    type: fetch
    source: https://github.com/oclaussen/dormouse/releases/download/v0.1.4/dormouse_0.1.4_Linux_x86_64.tar.gz
    unpack: dormouse
    destination: /bin/dormouse

  gpghome:
    type: copy
    path: /home/dodo/.gnupg
    image: dodo/gpg

  awsconfig:
    type: copy
    path: /home/dodo/.aws
    image: dodo/aws

  setup:
    type: script
    script: |
      mkdir /certs /certs/client
      chmod 1777 /certs /certs/client
      mkdir /run/user
      chmod 1777 /run/user
      mkdir -p /home/dodo/.local/share/docker
      chown -R dodo:dodo /home/dodo/.local/share/docker
