backdrops:
  docker:
    forward_stage: true
    image:
      name: dodo/docker
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
      - '{{ projectRoot }}:/build'
    working_dir: '/build/{{ projectPath }}'
    script: exec dormouse /dormouse.yaml "$@"

  ctop:
    forward_stage: true
    image:
      name: dodo/docker
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    script: exec ctop "$@"
