---
exec: ['/bin/docker']
subcommands:
  sh:
    exec: ['/bin/bash']
  compose:
    exec: ['/bin/docker-compose']
  ecr:
    options:
      - name: profile
        default: default
    env:
      AWS_VAULT_BACKEND: pass
      AWS_VAULT_PASS_CMD: /bin/gopass
      AWS_VAULT_PASS_PASSWORD_STORE_DIR: /data/passwords/aws-vault
    exec: ['/bin/aws-vault', 'exec', '{{ profile }}', '--', 'docker']
  host:
    exec:
      - '/bin/docker'
      - 'run'
      - '-it'
      - '--rm'
      - '--privileged'
      - '--net=host'
      - '--pid=host'
      - '--ipc=host'
      - '--volume'
      - '/:/host'
      - 'busybox'
      - 'chroot'
      - '/host'
