# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo

  syft:
    type: fetch
    source: https://github.com/anchore/syft/releases/download/v0.83.0/syft_0.83.0_linux_amd64.tar.gz
    unpack: syft
    destination: /bin/syft
