# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo
  dotfiles: home

env:
  PATH: /opt/python/bin

packages:
  name:
    - curl
    - gnupg
    - groff
    - jq
    - less
    - git

download:
  - source: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
    destination: /tmp/session-manager-plugin.deb

  - source: https://github.com/gopasspw/gopass/releases/download/v1.14.3/gopass-1.14.3-linux-amd64.tar.gz
    unpack: gopass
    destination: /bin/gopass

  - source: https://github.com/99designs/aws-vault/releases/download/v6.6.0/aws-vault-linux-amd64
    destination: /bin/aws-vault

  - source: https://github.com/wabenet/dormouse/releases/download/v0.1.4/dormouse_0.1.4_Linux_x86_64.tar.gz
    unpack: dormouse
    destination: /bin/dormouse

from:
  - image: dodo/gpg
    path: /home/dodo/.gnupg
  - directory: root
    path: /

  - dockerfile: |
      FROM dodo/languages/python
      ENV PATH /opt/python/bin:$PATH
      RUN pip3 install argparse awscli boto3
    path: /opt/python

run:
  - script: dpkg -i /tmp/session-manager-plugin.deb
