# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo

download:
  - source: https://github.com/VirtusLab/render/releases/download/v0.1.3/render-linux-amd64
    destination: /bin/render
