# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo

  packages:
    type: install
    name: libswscale5 libgraphicsmagick++-q16-12 libturbojpeg0 libexif12 libavcodec58 libavformat58 libavdevice58 libopenslide0

  timg:
    type: copy
    path: /bin/timg
    dockerfile: |
      FROM dodo/base

      RUN apt-get update \
       && apt-get install -y \
          cmake git g++ pkg-config \
          libgraphicsmagick++-dev libturbojpeg-dev libexif-dev libswscale-dev \
          libavcodec-dev libavformat-dev libavdevice-dev \
          libopenslide-dev

      WORKDIR /timg
      RUN git init \
       && git remote add origin https://github.com/hzeller/timg.git \
       && git fetch origin v1.4.2 \
       && git reset --hard FETCH_HEAD

      RUN mkdir -p build && cd build \
       && cmake ../ -DWITH_VIDEO_DECODING=On -DWITH_OPENSLIDE_SUPPORT=On \
       && make \
       && mv src/timg /bin/timg
