# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo
  dotfiles: home

env:
  PATH: /home/dodo/.krew/bin:/opt/python/bin:/usr/local/bin
  KUBECONFIG: /home/dodo/.kube/context.yaml:/home/dodo/.kubeconfig:/home/dodo/.kube/config

  AWS_VAULT_BACKEND: pass
  AWS_VAULT_PASS_CMD: /bin/gopass
  AWS_VAULT_PASS_PASSWORD_STORE_DIR: /data/passwords/aws-vault

packages:
  name:
    - git
    - gnupg
    - ncurses-bin
    - vim

download:
  - source: https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
    destination: /bin/kubectl

  - source: https://github.com/derailed/k9s/releases/download/v0.23.10/k9s_Linux_x86_64.tar.gz
    unpack: k9s
    destination: /bin/k9s

  - source: https://github.com/derailed/popeye/releases/download/v0.9.7/popeye_Linux_x86_64.tar.gz
    unpack: popeye
    destination: /bin/popeye

  - source: https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-linux-amd64
    destination: /bin/kind

  - source: https://get.helm.sh/helm-v3.7.2-linux-amd64.tar.gz
    unpack: linux-amd64/helm
    destination: /bin/helm

  - source: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.10.0/kustomize_v3.10.0_linux_amd64.tar.gz
    unpack: kustomize
    destination: /bin/kustomize

  - source: https://github.com/fluxcd/flux2/releases/download/v0.5.7/flux_0.5.7_linux_amd64.tar.gz
    unpack: flux
    destination: /bin/flux

  - source: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.19.0/crictl-v1.19.0-linux-amd64.tar.gz
    unpack: crictl
    destination: /bin/crictl

  - source: https://github.com/armosec/kubescape/releases/download/v1.0.133/kubescape-ubuntu-latest
    destination: /bin/kubescape

  - source: https://github.com/gopasspw/gopass/releases/download/v1.14.3/gopass-1.14.3-linux-amd64.tar.gz
    unpack: gopass
    destination: /bin/gopass

  - source: https://github.com/99designs/aws-vault/releases/download/v6.6.0/aws-vault-linux-amd64
    destination: /bin/aws-vault

  - source: https://github.com/linkerd/linkerd2/releases/download/edge-22.10.3/linkerd2-cli-edge-22.10.3-linux-amd64
    destination: /bin/linkerd


from:
  - image: docker:19.03.1
    path: /usr/local/bin/docker

  - dockerfile: |
      FROM dodo/languages/python
      ENV PATH /opt/python/bin:$PATH
      RUN pip3 install awscli
    path: /opt/python

  - dockerfile: |
      FROM dodo/languages/buildbase

      RUN apt-get update && apt-get -y install git

      RUN curl -L -o /bin/kubectl \
          https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl \
       && chmod +x /bin/kubectl

      RUN curl -L -o /tmp/krew.tar.gz \
          https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.tar.gz \
       && tar -xzf /tmp/krew.tar.gz -C /tmp \
       && curl -L -o /tmp/krew.yaml \
          https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.yaml

      RUN addgroup \
            --gid 1000 \
            dodo \
       && adduser \
            --uid 1000 \
            --gid 1000 \
            --gecos '' \
            --home /home/dodo \
            --shell /bin/bash \
            --disabled-password \
            dodo \
       && adduser dodo users

      USER dodo
      RUN /tmp/krew-linux_amd64 install --archive /tmp/krew.tar.gz --manifest /tmp/krew.yaml
      ENV PATH /home/dodo/.krew/bin:${PATH}

      RUN kubectl krew update \
       && kubectl krew install tree \
       && kubectl krew install ctx \
       && kubectl krew install ns \
       && kubectl krew install neat \
       && kubectl krew install view-secret \
       && kubectl krew install cert-manager
    path: /home/dodo/.krew

  - image: dodo/gpg
    path: /home/dodo/.gnupg
  - image: dodo/aws
    path: /home/dodo/.aws
