backdrops:
  kube:
    aliases: [kubectl]
    forward_stage: true
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
      - '{{ projectRoot }}:/build'
    working_dir: '/build/{{ projectPath }}'
    script: exec /bin/kubectl "$@"

  k9s:
    name: k9s
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
    script: exec /bin/k9s "$@"

  popeye:
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
    script: exec /bin/popeye "$@"

  kind:
    forward_stage: true
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
    script: exec /bin/kind "$@"
