backdrops:
  kube:
    aliases: [kubectl]
    forward_stage: true
    image:
      name: dodo/kube
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-data:/data/gpg'
      - 'passwords:/home/dodo/.password-store'
      - '{{ projectRoot }}:/build'
    environment:
      - 'GNUPGHOME=/data/gpg'
    working_dir: '/build/{{ projectPath }}'
    script: exec /bin/kubectl "$@"

  k9s:
    name: k9s
    image:
      name: dodo/kube
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-data:/data/gpg'
      - 'passwords:/home/dodo/.password-store'
    environment:
      - 'GNUPGHOME=/data/gpg'
    script: exec /bin/k9s "$@"

  popeye:
    image:
      name: dodo/kube
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-data:/data/gpg'
      - 'passwords:/home/dodo/.password-store'
    environment:
      - 'GNUPGHOME=/data/gpg'
    script: exec /bin/popeye "$@"

  kind:
    forward_stage: true
    image:
      name: dodo/kube
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
    script: exec /bin/kind "$@"
