backdrops:
  kubectl:
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
      - '{{ projectRoot }}:/build'
    working_dir: '/build/{{ projectPath }}'
    script: |
      test -f /home/dodo/.kube/context.yaml || cp /home/dodo/context.yaml /home/dodo/.kube/context.yaml
      if [ "$1" = "debug" ]; then
        shift
        exec kubectl run -i --rm --tty debug --image=alpine:latest --restart=Never "$@" -- sh
      else
        exec /bin/kubectl "$@"
      fi

  helm:
    forward_stage: true
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
      - 'helm:/home/dodo/.cache/helm'
      - '{{ projectRoot }}:/build'
    working_dir: '/build/{{ projectPath }}'
    script: exec /bin/helm "$@"

  k9s:
    name: k9s
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    ports: '8080:8080'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
    script: exec /bin/k9s "$@"

  crictl:
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - '/run/containerd/containerd.sock:/run/containerd/containerd.sock'
    script: exec /bin/crictl "$@"

  flux:
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    environment:
      - 'KUBECONFIG=/home/dodo/.kubeconfig'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
    script: exec /bin/flux "$@"

  popeye:
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
      - 'gpg-agent:/data/gpg-agent'
      - 'passwords:/data/passwords'
    script: exec /bin/popeye "$@"

  kind:
    forward_stage: true
    image:
      name: dodo/kube
      requires: [dodo/base, dodo/gpg, dodo/aws]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'kubeconfig:/home/dodo/.kube'
    script: exec /bin/kind "$@"
