# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  packages:
    type: install
    name: git gnupg libsqlite3-0 xz-utils

  env:
    type: environment
    variables:
      PATH: /opt/google-cloud-sdk/bin:/opt/python/bin

  gcpsdk:
    type: fetch
    source: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-320.0.0-linux-x86_64.tar.gz
    destination: /tmp/google-cloud-sdk.tar.gz

  gam:
    type: fetch
    source: https://github.com/jay0lee/GAM/releases/download/v6.06/gam-6.06-linux-x86_64-legacy.tar.xz
    destination: /tmp/gam.tar.xz

  gpghome:
    type: copy
    path: /home/dodo/.gnupg
    image: dodo/gpg

  pass:
    type: copy
    path: /bin/gopass
    image: dodo/pass

  passconfig:
    type: copy
    path: /home/dodo/.config/gopass
    image: dodo/pass

  python:
    type: copy
    path: /opt/python
    image: dodo/languages/python

  installsdk:
    type: script
    script: tar -xvzf /tmp/google-cloud-sdk.tar.gz -C /opt

  installgam:
    type: script
    user: dodo
    cwd: /home/dodo
    script: |
      tar -xvf /tmp/gam.tar.xz -C .
      touch gam/noshorturls.txt
