# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  packages:
    type: install
    name: gnupg

  jira:
    type: fetch
    source: https://github.com/go-jira/jira/releases/download/v1.0.26/jira-linux-amd64
    destination: /bin/jira

  gpghome:
    type: copy
    path: /home/dodo/.gnupg
    image: dodo/gpg

  pass:
    type: copy
    path: /bin/gopass
    image: dodo/pass

  passconfig:
    type: copy
    path: /home/dodo/.config/gopass
    image: dodo/pass

  jiraui:
    type: copy
    path: /bin/jira-ui
    dockerfile: |
      FROM dodo/languages/golang
      ENV PATH /opt/go/bin:$PATH
      RUN apt-get update && apt-get -y install git
      RUN git clone https://github.com/mikepea/go-jira-ui /jira-ui
      WORKDIR /jira-ui
      RUN go build -o bin/jira-ui ./jira-ui \
       && cp ./bin/* /bin/
