# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo

  packages:
    type: install
    name: gettext gnupg openssh-client sshpass zip

  env:
    type: environment
    variables:
      PATH: /opt/python/bin

  sops:
    type: fetch
    source: https://github.com/mozilla/sops/releases/download/v3.6.1/sops-v3.6.1.linux
    destination: /bin/sops

  ansible:
    type: copy
    path: /opt/python
    dockerfile: |
      FROM dodo/languages/buildbase
      COPY --from=dodo/languages/python /opt/python /opt/python
      COPY --from=dodo/languages/rust /opt/rust /opt/rust
      ENV RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo
      ENV PATH /opt/python/bin:${CARGO_HOME}/bin:$PATH
      RUN pip3 install ansible pywinrm

  gpghome:
    type: copy
    path: /home/dodo/.gnupg
    image: dodo/gpg
