backdrops:
  ansible:
    image:
      name: dodo/ansible
      steps: |
        # syntax = oclaussen/dodfile-syntax
        base_image: dodo/base
        user:
          name: dodo
        env:
          PATH: /opt/python/bin
        packages:
          name:
            - gettext
            - openssh-client
            - sshpass
            - zip
        from:
          - dockerfile: |
              FROM dodo/languages/python
              ENV PATH /opt/python/bin:$PATH
              RUN pip3 install ansible pywinrm
            path: /opt/python
    volumes:
      - 'gpg-agent:/data/gpg-agent'
      - '{{ projectRoot }}:/build'
    environment:
      - SSH_AUTH_SOCK=/data/gpg-agent/S.gpg-agent.ssh
      - ANSIBLE_HOST_KEY_CHECKING=False
    working_dir: '/build/{{ projectPath }}'
    script: exec ansible-playbook "$@"
