backdrops:
  ansible:
    image:
      name: dodo/ansible
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - '{{ projectRoot }}:/build'
    working_dir: '/build/{{ projectPath }}'
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    script: exec ansible-playbook "$@"
