backdrops:
  ansible:
    image:
      name: dodo/ansible
      requires: [dodo/base]
      context: '{{ currentDir }}'
      dockerfile: '{{ currentDir }}/Dockerfile'
    volumes:
      - 'gpg-agent:/data/gpg-agent'
      - '{{ projectRoot }}:/build'
    environment:
      - SSH_AUTH_SOCK=/data/gpg-agent/S.gpg-agent.ssh
      - ANSIBLE_HOST_KEY_CHECKING=False
    working_dir: '/build/{{ projectPath }}'
    script: exec ansible-playbook "$@"
