# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo
  dotfiles: home

env:
  PATH: /home/dodo/bin

packages:
  name:
    - git
    - git-lfs
    - gnupg
    - less
    - openssh-client
    - vim

download:
  - source: https://github.com/gopasspw/gopass/releases/download/v1.8.6/gopass-1.8.6-linux-amd64.tar.gz
    unpack: gopass-1.8.6-linux-amd64/gopass
    destination: /bin/gopass

  - source: https://github.com/oclaussen/chirp/releases/download/v2.0.0/chirp_2.0.0_Linux_x86_64.tar.gz
    unpack: chirp
    destination: /bin/chirp

from:
  - image: dodo/gpg
    path: /home/dodo/.gnupg
  - directory: root
    path: /
