# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  packages:
    type: install
    name: git git-lfs gnupg less openssh-client vim

  env:
    type: environment
    variables:
      PATH: /home/dodo/bin

  pass:
    type: fetch
    source: https://github.com/gopasspw/gopass/releases/download/v1.8.6/gopass-1.8.6-linux-amd64.tar.gz
    unpack: gopass-1.8.6-linux-amd64/gopass
    destination: /bin/gopass

  chirp:
    type: fetch
    source: https://github.com/oclaussen/chirp/releases/download/v2.0.0/chirp_2.0.0_Linux_x86_64.tar.gz
    unpack: chirp
    destination: /bin/chirp

  gpghome:
    type: copy
    path: /home/dodo/.gnupg
    image: dodo/gpg

  files:
    type: copy
    path: /
    directory: root
