# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo
  dotfiles: home

env:
  RUSTUP_HOME: /opt/rust/rustup
  CARGO_HOME: /opt/rust/cargo
  PATH: /opt/rust/cargo/bin:$PATH

packages:
  name:
    - less
    - man
    - procps
    - zsh

download:
  - source: https://github.com/oclaussen/chirp/releases/download/v2.0.0/chirp_2.0.0_Linux_x86_64.tar.gz
    unpack: chirp
    destination: /bin/chirp

  - source: https://github.com/junegunn/fzf-bin/releases/download/0.19.0/fzf-0.19.0-linux_amd64.tgz
    unpack: fzf
    destination: /bin/fzf

from:
  - dockerfile: |
      FROM dodo/languages/rust
      ENV RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo
      ENV PATH ${CARGO_HOME}/bin:$PATH

      RUN apt-get update && apt-get install -y clang libssl-dev make pkg-config

      RUN cargo install \
          bat \
          exa \
          fd-find \
          procs \
          ripgrep \
          sd \
          starship \
          tokei \
          xsv
    path: /opt/rust

  - dockerfile: |
      FROM dodo/languages/golang
      ENV PATH /opt/go/bin:$PATH
      WORKDIR /dodo

      RUN apt-get update && apt-get install -y git

      RUN git init \
       && git remote add origin https://github.com/dodo-cli/dodo \
       && git fetch origin main \
       && git reset --hard 8c47d24
      
      ADD generate.yaml .
      RUN go generate . && go build . && mv dodo /bin/dodo
    path: /bin/dodo
