# syntax = wabenet/dodfile-syntax
actions:
  base:
    type: base
    name: dodo/base

  dodo:
    type: user
    name: dodo
    dotfiles: home

  packages:
    type: install
    name: less man procps zsh

  env:
    type: environment
    variables:
      RUSTUP_HOME: /opt/rust/rustup
      CARGO_HOME: /opt/rust/cargo
      PATH: /opt/rust/cargo/bin:$PATH

  chirp:
    type: fetch
    source: https://github.com/oclaussen/chirp/releases/download/v2.0.0/chirp_2.0.0_Linux_x86_64.tar.gz
    unpack: chirp
    destination: /bin/chirp

  fzf:
    type: fetch
    source: https://github.com/junegunn/fzf-bin/releases/download/0.19.0/fzf-0.19.0-linux_amd64.tgz
    unpack: fzf
    destination: /bin/fzf

  tools:
    type: copy
    path: /opt/rust
    dockerfile: |
      FROM dodo/languages/rust
      ENV RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo
      ENV PATH ${CARGO_HOME}/bin:$PATH

      COPY --from=dodo/languages/python /opt/python /opt/python
      ENV PATH /opt/python/bin:$PATH

      RUN apt-get update && apt-get install -y clang cmake libssl-dev make pkg-config

      RUN cargo install \
          bat \
          exa \
          fd-find \
          procs \
          ripgrep \
          sd \
          starship \
          tokei \
          xsv

  dodo:
    type: copy
    path: /bin/dodo
    dockerfile: |
      FROM dodo/languages/golang
      ENV PATH /opt/go/bin:$PATH
      WORKDIR /dodo

      RUN apt-get update && apt-get install -y git

      RUN git init \
       && git remote add origin https://github.com/wabenet/dodo \
       && git fetch origin main \
       && git reset --hard 83b6cba
      
      ADD generate.yaml .
      RUN go generate . && go build . && mv dodo /bin/dodo
