add_newline = false
prompt_order = ["directory", "character"]

[character]
symbol = "("
vimcmd_symbol = "|"
style_success = "fg:blue"
style_failure = "fg:red"

[directory]
format = '[\(](blue)[$path](yellow)[\)-](blue)'
