# syntax = oclaussen/dodfile-syntax
base_image: dodo/base

user:
  name: dodo

packages:
  name:
    - curl
    - dnsutils
    - iperf3
    - traceroute
    - wget

download:
  - source: https://github.com/jreisinger/checkip/releases/download/v0.24.5/checkip_0.24.5_linux_amd64.tar.gz
    unpack: checkip
    destination: /bin/checkip
